"""Provider-neutral infrastructure for future authenticated write tools."""

from app.write_operations.contracts import (
    BaseWriteOperation,
    WriteAuditEvent,
    WriteError,
    WriteExecutionContext,
    WriteFailurePhase,
    WriteResult,
    WriteSecurityEnvelope,
    WriteStatus,
    WriteValidationDecision,
)
from app.write_operations.executor import (
    WriteExecutionContractError,
    WriteFrameworkExecutor,
    WriteSecurityBoundaryError,
)
from app.write_operations.transaction import (
    SQLAlchemyTransactionManager,
    TransactionManager,
    WriteTransactionError,
)
from app.write_operations.order_cancellation import (
    CANCELLABLE_ORDER_STATUSES,
    CancelOrderInput,
    CancelOrderOperation,
    CancelOrderOutput,
    OrderCancellationPolicy,
    OrderCancellationSnapshot,
    SQLAlchemyOrderCancellationReader,
    SQLAlchemyOrderCancellationStore,
)
from app.write_operations.delivery_address_update import (
    ADDRESS_UPDATE_ELIGIBLE_STATUSES,
    MAX_DELIVERY_ADDRESS_LENGTH,
    AddressUpdatePolicy,
    AddressUpdateSnapshot,
    SQLAlchemyAddressUpdateReader,
    SQLAlchemyAddressUpdateStore,
    UpdateDeliveryAddressInput,
    UpdateDeliveryAddressOperation,
    UpdateDeliveryAddressOutput,
    normalize_delivery_address,
)
from app.write_operations.refund_initiation import (
    InitiateRefundInput,
    InitiateRefundOperation,
    InitiateRefundOutput,
    RefundInitiationSnapshot,
    RefundPolicy,
    SQLAlchemyRefundInitiationReader,
    SQLAlchemyRefundInitiationStore,
)
from app.write_operations.support_ticket_creation import (
    CreateSupportTicketInput,
    CreateSupportTicketOperation,
    CreateSupportTicketOutput,
    SQLAlchemySupportTicketReader,
    SQLAlchemySupportTicketStore,
    SupportTicketPolicy,
    SupportTicketSnapshot,
)

__all__ = [
    "BaseWriteOperation",
    "ADDRESS_UPDATE_ELIGIBLE_STATUSES",
    "MAX_DELIVERY_ADDRESS_LENGTH",
    "AddressUpdatePolicy",
    "AddressUpdateSnapshot",
    "CANCELLABLE_ORDER_STATUSES",
    "CancelOrderInput",
    "CancelOrderOperation",
    "CancelOrderOutput",
    "CreateSupportTicketInput",
    "CreateSupportTicketOperation",
    "CreateSupportTicketOutput",
    "InitiateRefundInput",
    "InitiateRefundOperation",
    "InitiateRefundOutput",
    "OrderCancellationPolicy",
    "OrderCancellationSnapshot",
    "RefundInitiationSnapshot",
    "RefundPolicy",
    "SQLAlchemyTransactionManager",
    "SQLAlchemyOrderCancellationReader",
    "SQLAlchemyOrderCancellationStore",
    "SQLAlchemyRefundInitiationReader",
    "SQLAlchemyRefundInitiationStore",
    "SQLAlchemySupportTicketReader",
    "SQLAlchemySupportTicketStore",
    "SupportTicketPolicy",
    "SupportTicketSnapshot",
    "SQLAlchemyAddressUpdateReader",
    "SQLAlchemyAddressUpdateStore",
    "TransactionManager",
    "WriteAuditEvent",
    "WriteError",
    "WriteExecutionContext",
    "WriteExecutionContractError",
    "WriteFailurePhase",
    "WriteFrameworkExecutor",
    "WriteResult",
    "WriteSecurityBoundaryError",
    "WriteSecurityEnvelope",
    "WriteStatus",
    "WriteTransactionError",
    "WriteValidationDecision",
    "UpdateDeliveryAddressInput",
    "UpdateDeliveryAddressOperation",
    "UpdateDeliveryAddressOutput",
    "normalize_delivery_address",
]
