"""create tool call table

Revision ID: 14deb9bff24c
Revises: 60ab3b4ce639
Create Date: 2026-07-16 13:50:10.779760
"""

from typing import Optional, Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision: str = '14deb9bff24c'
down_revision: Optional[str] = '60ab3b4ce639'
branch_labels: Optional[Union[str, Sequence[str]]] = None
depends_on: Optional[Union[str, Sequence[str]]] = None


def upgrade() -> None:
    """Apply this migration."""

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tool_calls',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('model_run_id', sa.UUID(), nullable=False),
    sa.Column('tool_name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('input_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('output_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('success', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('requested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('requested', 'approved', 'executing', 'completed', 'failed', 'rejected')", name=op.f('ck_tool_calls_valid_status')),
    sa.CheckConstraint('finished_at IS NULL OR finished_at >= requested_at', name=op.f('ck_tool_calls_finished_at_not_before_requested_at')),
    sa.CheckConstraint('latency_ms IS NULL OR latency_ms >= 0', name=op.f('ck_tool_calls_non_negative_latency_ms')),
    sa.CheckConstraint('started_at IS NULL OR finished_at IS NULL OR finished_at >= started_at', name=op.f('ck_tool_calls_finished_at_not_before_started_at')),
    sa.CheckConstraint('started_at IS NULL OR started_at >= requested_at', name=op.f('ck_tool_calls_started_at_not_before_requested_at')),
    sa.CheckConstraint('success = false OR error_message IS NULL', name=op.f('ck_tool_calls_error_message_only_on_failure')),
    sa.ForeignKeyConstraint(['model_run_id'], ['model_runs.id'], name=op.f('fk_tool_calls_model_run_id_model_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tool_calls'))
    )
    op.create_index('ix_tool_calls_model_run_id', 'tool_calls', ['model_run_id'], unique=False)
    op.create_index('ix_tool_calls_requested_at', 'tool_calls', ['requested_at'], unique=False)
    op.create_index('ix_tool_calls_status', 'tool_calls', ['status'], unique=False)
    op.create_index('ix_tool_calls_tool_name', 'tool_calls', ['tool_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert this migration."""

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tool_calls_tool_name', table_name='tool_calls')
    op.drop_index('ix_tool_calls_status', table_name='tool_calls')
    op.drop_index('ix_tool_calls_requested_at', table_name='tool_calls')
    op.drop_index('ix_tool_calls_model_run_id', table_name='tool_calls')
    op.drop_table('tool_calls')
    # ### end Alembic commands ###
