"""create conversation and message tables

Revision ID: 51be6b760964
Revises: dba8a6e4b6bf
Create Date: 2026-07-14 16:25:32.488344
"""

from typing import Optional, Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = '51be6b760964'
down_revision: Optional[str] = 'dba8a6e4b6bf'
branch_labels: Optional[Union[str, Sequence[str]]] = None
depends_on: Optional[Union[str, Sequence[str]]] = None


def upgrade() -> None:
    """Apply this migration."""

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('related_order_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('channel', sa.String(length=32), nullable=False),
    sa.Column('active_model', sa.String(length=100), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("channel IN ('web', 'mobile', 'whatsapp', 'internal_test')", name=op.f('ck_conversations_valid_channel')),
    sa.CheckConstraint("status IN ('open', 'waiting_for_customer', 'waiting_for_agent', 'resolved', 'escalated', 'closed')", name=op.f('ck_conversations_valid_status')),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_conversations_customer_id_customers'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['related_order_id'], ['orders.id'], name=op.f('fk_conversations_related_order_id_orders'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conversations'))
    )
    op.create_index('ix_conversations_customer_id', 'conversations', ['customer_id'], unique=False)
    op.create_index('ix_conversations_related_order_id', 'conversations', ['related_order_id'], unique=False)
    op.create_index('ix_conversations_status', 'conversations', ['status'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('language', sa.String(length=32), nullable=True),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("language IS NULL OR language IN ('egyptian_arabic', 'arabic', 'franco_arabic', 'english', 'mixed', 'unknown')", name=op.f('ck_messages_valid_language')),
    sa.CheckConstraint("role IN ('user', 'assistant', 'system', 'tool')", name=op.f('ck_messages_valid_role')),
    sa.CheckConstraint('char_length(trim(content)) > 0', name=op.f('ck_messages_non_empty_content')),
    sa.CheckConstraint('sequence_number > 0', name=op.f('ck_messages_positive_sequence_number')),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('fk_messages_conversation_id_conversations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_messages')),
    sa.UniqueConstraint('conversation_id', 'sequence_number', name='uq_messages_conversation_id_sequence_number')
    )
    op.create_index('ix_messages_conversation_id', 'messages', ['conversation_id'], unique=False)
    op.create_index('ix_messages_created_at', 'messages', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert this migration."""

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_messages_created_at', table_name='messages')
    op.drop_index('ix_messages_conversation_id', table_name='messages')
    op.drop_table('messages')
    op.drop_index('ix_conversations_status', table_name='conversations')
    op.drop_index('ix_conversations_related_order_id', table_name='conversations')
    op.drop_index('ix_conversations_customer_id', table_name='conversations')
    op.drop_table('conversations')
    # ### end Alembic commands ###
