"""create model run table

Revision ID: 60ab3b4ce639
Revises: 51be6b760964
Create Date: 2026-07-14 16:50:11.001869
"""

from typing import Optional, Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = '60ab3b4ce639'
down_revision: Optional[str] = '51be6b760964'
branch_labels: Optional[Union[str, Sequence[str]]] = None
depends_on: Optional[Union[str, Sequence[str]]] = None


def upgrade() -> None:
    """Apply this migration."""

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('estimated_cost', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('temperature', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("provider IN ('gemini', 'qwen', 'fanar')", name=op.f('ck_model_runs_valid_provider')),
    sa.CheckConstraint("status IN ('running', 'completed', 'failed', 'cancelled')", name=op.f('ck_model_runs_valid_status')),
    sa.CheckConstraint('estimated_cost IS NULL OR estimated_cost >= 0', name=op.f('ck_model_runs_non_negative_estimated_cost')),
    sa.CheckConstraint('input_tokens IS NULL OR input_tokens >= 0', name=op.f('ck_model_runs_non_negative_input_tokens')),
    sa.CheckConstraint('latency_ms IS NULL OR latency_ms >= 0', name=op.f('ck_model_runs_non_negative_latency_ms')),
    sa.CheckConstraint('output_tokens IS NULL OR output_tokens >= 0', name=op.f('ck_model_runs_non_negative_output_tokens')),
    sa.CheckConstraint('success = false OR error_message IS NULL', name=op.f('ck_model_runs_error_message_only_on_failure')),
    sa.CheckConstraint('temperature IS NULL OR (temperature >= 0 AND temperature <= 2)', name=op.f('ck_model_runs_valid_temperature_range')),
    sa.CheckConstraint('total_tokens IS NULL OR total_tokens >= 0', name=op.f('ck_model_runs_non_negative_total_tokens')),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('fk_model_runs_conversation_id_conversations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_model_runs'))
    )
    op.create_index('ix_model_runs_conversation_id', 'model_runs', ['conversation_id'], unique=False)
    op.create_index('ix_model_runs_provider', 'model_runs', ['provider'], unique=False)
    op.create_index('ix_model_runs_started_at', 'model_runs', ['started_at'], unique=False)
    op.create_index('ix_model_runs_status', 'model_runs', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert this migration."""

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_model_runs_status', table_name='model_runs')
    op.drop_index('ix_model_runs_started_at', table_name='model_runs')
    op.drop_index('ix_model_runs_provider', table_name='model_runs')
    op.drop_index('ix_model_runs_conversation_id', table_name='model_runs')
    op.drop_table('model_runs')
    # ### end Alembic commands ###
