"""create knowledge article tables

Revision ID: dcc77b6799fd
Revises: e89711ecf573
Create Date: 2026-07-25 23:06:49.375847
"""

from typing import Optional, Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = 'dcc77b6799fd'
down_revision: Optional[str] = 'e89711ecf573'
branch_labels: Optional[Union[str, Sequence[str]]] = None
depends_on: Optional[Union[str, Sequence[str]]] = None


def upgrade() -> None:
    """Apply this migration."""

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_articles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('language', sa.String(length=16), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("category IN ('policy', 'faq', 'orders', 'delivery', 'payment', 'refund')", name=op.f('ck_knowledge_articles_valid_knowledge_category')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_knowledge_articles')),
    sa.UniqueConstraint('slug', 'language', name='uq_knowledge_articles_slug_language')
    )
    op.create_index('ix_knowledge_articles_category_active', 'knowledge_articles', ['category', 'is_active'], unique=False)
    op.create_table('knowledge_article_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('article_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=240), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_published', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['knowledge_articles.id'], name=op.f('fk_knowledge_article_versions_article_id_knowledge_articles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_knowledge_article_versions')),
    sa.UniqueConstraint('article_id', 'version', name='uq_knowledge_article_versions_article_version')
    )
    op.create_index('ix_knowledge_versions_article_published', 'knowledge_article_versions', ['article_id', 'is_published', 'published_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert this migration."""

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_knowledge_versions_article_published', table_name='knowledge_article_versions')
    op.drop_table('knowledge_article_versions')
    op.drop_index('ix_knowledge_articles_category_active', table_name='knowledge_articles')
    op.drop_table('knowledge_articles')
    # ### end Alembic commands ###
