"""create refund domain tables

Revision ID: e89711ecf573
Revises: e84f21c7d930
Create Date: 2026-07-25 22:41:44.872371
"""

from typing import Optional, Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = 'e89711ecf573'
down_revision: Optional[str] = 'e84f21c7d930'
branch_labels: Optional[Union[str, Sequence[str]]] = None
depends_on: Optional[Union[str, Sequence[str]]] = None


def upgrade() -> None:
    """Apply this migration."""

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refund_eligibilities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('public_reason', sa.Text(), nullable=False),
    sa.Column('assessed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('eligible', 'not_eligible', 'undetermined')", name=op.f('ck_refund_eligibilities_valid_refund_eligibility_status')),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_refund_eligibilities_order_id_orders'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refund_eligibilities')),
    sa.UniqueConstraint('order_id', name='uq_refund_eligibilities_order_id')
    )
    op.create_index('ix_refund_eligibilities_order_id', 'refund_eligibilities', ['order_id'], unique=False)
    op.create_table('refunds',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('payment_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('public_reason', sa.Text(), nullable=True),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'processing', 'completed', 'rejected')", name=op.f('ck_refunds_valid_refund_status')),
    sa.CheckConstraint('amount IS NULL OR amount >= 0', name=op.f('ck_refunds_non_negative_refund_amount')),
    sa.CheckConstraint('char_length(currency) = 3', name=op.f('ck_refunds_valid_refund_currency')),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], name=op.f('fk_refunds_payment_id_payments'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refunds'))
    )
    op.create_index('ix_refunds_payment_created', 'refunds', ['payment_id', 'created_at'], unique=False)
    op.create_table('refund_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('refund_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('public_description', sa.Text(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("event_type IN ('requested', 'processing', 'completed', 'rejected')", name=op.f('ck_refund_events_valid_refund_event_type')),
    sa.ForeignKeyConstraint(['refund_id'], ['refunds.id'], name=op.f('fk_refund_events_refund_id_refunds'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refund_events'))
    )
    op.create_index('ix_refund_events_refund_occurred', 'refund_events', ['refund_id', 'occurred_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert this migration."""

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_refund_events_refund_occurred', table_name='refund_events')
    op.drop_table('refund_events')
    op.drop_index('ix_refunds_payment_created', table_name='refunds')
    op.drop_table('refunds')
    op.drop_index('ix_refund_eligibilities_order_id', table_name='refund_eligibilities')
    op.drop_table('refund_eligibilities')
    # ### end Alembic commands ###
